apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 5m
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      labels:
        dominodatalab.com/domino-node: "true"
        dominodatalab.com/node-pool: default-gpu
        nvidia.com/gpu: "true"
    spec:
      limits:
        cpu: 80
        memory: 320Gi
        nvidia.com/gpu: 10
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: domino-eks-gpu
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - reserved
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["g4dn.xlarge"]
      startupTaints:
        - effect: NoExecute
          key: ebs.csi.aws.com/agent-not-ready
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu
          value: "true"
