apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: trainium
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 5m
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      labels:
        aws.amazon.com/neuron: "true"
        dominodatalab.com/domino-node: "true"
        dominodatalab.com/node-pool: trainium
    spec:
      limits:
        aws.amazon.com/neuron: 10
        cpu: 80
        memory: 320Gi
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: domino-eks-neuron
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - reserved
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["trn1.2xlarge"]
      startupTaints:
        - effect: NoExecute
          key: ebs.csi.aws.com/agent-not-ready
      taints:
        - effect: NoSchedule
          key: aws.amazon.com/neuron
          value: "true"
