apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: domino-eks-platform
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        encrypted: true
        volumeSize: 100Gi
        volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: ${EKS_CLUSTER_NAME}-eks-nodes ## TODO: change to the role for the EKS nodes
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${EKS_CLUSTER_NAME} # TODO: update to the discovery tag for the cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${EKS_CLUSTER_NAME} # TODO: update to the discovery tag for the cluster
